### ISSUE TITLE
values not resolved when multiple occurrences exist

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/async-helpers#1]
Strangely, this problem is happening with a sync helper.

This is the reduced test case:
-  `name` is a property on the context
- the value of `name` should be `reflinks`
- `shorten` is a sync helper that simply strips `helper-` from the string passed to it. so `helper-reflinks` becomes `reflinks`

The following:

``` js
{% var nickname = shorten(name) %}

{%= nickname %}
{%= nickname %}
```

Renders to:

``` js
reflinks
__async_0_0__
```

**Comment by doowb** [comment]
This should be updated in `engine-cache` too because that's where the actual replacement is happening. It's only replacing 1 of the tags since the logic loops over ids and finds them in the string to replace them when the helper is resolved. Probably just needs to do a global replace.

Also, could update here to only wrap helpers if they have the `.async` flag enabled on them. Otherwise, just return the normal helper.

**Comment by doowb** [comment]
Actually... doesn't `str.replace()` always do a global replace?

**Comment by jonschlinkert** [comment]
> doesn't str.replace() always do a global replace?

if you do `str.replace('foo', 'bar')` that only replaces the first occurrence of `foo`. When regex is used it's the same, only first occurrence, unless the `g` flag is set.  but I'm using `.split()` not replace. 

> Probably just needs to do a global replace.

Do you mean the async code?

**Comment by doowb** [comment]
Resolving is done in `engine-cache` [here](https://github.com/jonschlinkert/engine-cache/blob/master/index.js#L224).

**Comment by jonschlinkert** [comment]
oh, yeah that's fine how it is. It should be `str = str.split(key).join(value);` though, since it's much faster - and _if_ there were multiple occurrences of the same ID, it would get them all.

**Comment by jonschlinkert** [comment]
just confirmed that `str = str.split(key).join(value);` in engine-cache solves this issue.

**Comment by jonschlinkert** [comment]
fixed when the above code was implemented
