### ISSUE TITLE
Callback is being sent as object

### ISSUE THREAD

**Issue by RamprasadAkella** [doowb/async-helpers#13]
```
` var upper = function (str, cb) {
        console.log(typeof cb)
        console.log('str', str, cb)
        return cb(null, str.toUpperCase())
      }`
```

I have registered an helper method "upper" as mentioned above, I am getting "cb" as an object not as a function when I am evaluating the template. Anyone has any idea on this ??

**Comment by doowb** [comment]
`async-helpers` will only add the `cb` to the existing arguments that are passed into the helper. If you are using `Handlebars`, then handlebars always adds an `options` object after any arguments that you pass in.

This means that normally your handlebars helper looks like:

```js
var upper = function(str, options) {
  return str.toUpperCase();
};
```

Even if you aren't using the `options` object, handlebars is still passing it in.

When `async-helpers` is used, the `cb` function is also passed in so your helper will need to look like this:

```js
var upper = function(str, options, cb) {
  return cb(null, str.toUpperCase());
};
```

If you are writing this helper so it can be used with multiple template engines, then you can check to see if the `options` object is a function first:

```js
var upper = function(str, options, cb) {
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }
  return cb(null, str.toUpperCase());
};
```

Hope this helps.

**Comment by RamprasadAkella** [comment]
@doowb  Thanks !

**Comment by jonschlinkert** [comment]
you should add that to the readme! great advice
