### ISSUE TITLE
Getting error as Unexpected token *

### ISSUE THREAD

**Issue by RamprasadAkella** [doowb/async-helpers#14]
When I am trying to require('async-helpers') in my code, I am getting this error saying Unexpected token *.

Is this something to do the node version ? I am using node version 0.12.7.

Though I am able to require from some of the files in my project.

```
AsyncHelpers.prototype.resolveId = function * (key) {
                                            ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:
```

**Comment by doowb** [comment]
Yes, `async-helpers` requires at least node 4.0. That `*` syntax is for JavaScript generator functions. You can use babel to transpile the code for an older version of node if necessary.

I'll probably be refactoring this code soon to remove the generator functions and be compatible with older versions of node.
