### ISSUE TITLE
ResolveIds method not waiting for callback

### ISSUE THREAD

**Issue by RamprasadAkella** [doowb/async-helpers#15]
I am calling resolveIds method, which in turn calling my async helper I have defined, but the resolveIds callback is being triggered even though I haven't return the callback from my helper method. And the Ids are being replaced with 'info' string. 
```
Before calling resolveIds method:
<doc>    <name>Joe</name>    <id>{$ASYNCID$0$0$}</id>  </doc>

<doc>    <name>Joe</name>    <id>info</id>  </doc>  
```

**Comment by doowb** [comment]
@RamprasadAkella will you add the code or point to a repository with the code showing what's happening?

**Comment by RamprasadAkella** [comment]
I have defined my helper function like below. So, when I call resolveIds method, the control is coming to the lookup helper, but somehow the resolveIds callback is being called before I call callback in the lookup helper.
Also I am creating two different AsyncHelpers instances while registering the helper and calling the resolveIds method, will that cause any problem ?

Lookup helper function:
```
    lookup: function (lookupName, lookupData, options, cb) { 
      var imp = model.import
      var connection = model.connection

      var impAdaptor
      try {
        impAdaptor = adaptors.createImportAdaptor(imp, connection)
      } catch (exp) {
        // TODO return error
      }

      var lookup = _.find(imp.http.lookups, {name: lookupName})
      var recordLookup = new HttpRecordLookup(null, lookup, impAdaptor)
      recordLookup.findValues(lookupData, function (err, lookupValues) {
        console.log('err', err, 'returning lookupValues', lookupValues)
        return cb(err, lookupValues)
      })
    }

  var asyncHelpers = new AsyncHelpers()
  _.forEach(helpers, function (helper, helperName) {
    helper.async = true
    asyncHelpers.set(helperName, helper)
  })
  var wrappedHelpers = asyncHelpers.get({wrap: true})
  Handlebars.registerHelper(wrappedHelpers)
```

Place where I am calling resolveIds:
```
  new AsyncHelpers().resolveIds(result.value, function (err, content) {
        logger.info('resolveIds', err, content)
        if (err) {
          records[index].errors.push(err)
        }
        evaluatedTemplates[index] = content
        return iterateeCallback()
      })
```

**Comment by doowb** [comment]
what does this line show:

```
console.log('err', err, 'returning lookupValues', lookupValues)
```

Also, what does the handlebars template look like that you're passing in, and what are the values of `lookupName` and `lookupData`?

This is tough to debug without more information since the output you showed before does replace an async id with some value. Since it gets replaced and there are no errors, then it seems like it might be a configuration issue. The above code looks fine (e.g. you don't return early from the `lookup` function and you're passing a value to the callback).

**Comment by RamprasadAkella** [comment]
Console.log is printing the value 3.
This is working for me now with the same code, not sure why this happened earlier, will debug and provide you some information if it happens again.

**Comment by doowb** [comment]
I'm glad you got it working.
