### ISSUE TITLE
Using async helpers multiple times in the template

### ISSUE THREAD

**Issue by RamprasadAkella** [doowb/async-helpers#16]
My template is like below, in which "lookup" is the async helper. I am using it at two places, does this module support this kind of usage ? Because I am getting the below error even though I return correctly from my helper method.
Template:

     ```
           '<createRequest>' +
                '{{#each data}}' +
                '  <doc>' +
                '    <name>{{this.name}}</name>' +
                '    <id>{{lookup "id" this}}</id>' +
                '    <items>' +
                '       {{#each this.items}}' +
                '       <item>' +
                '         <name>{{lookup "itemName" ../this}}</name>' +
                '       </item>' +
                '      {{/each}}' +
                '    </items>   ' +
                '  </doc>' +
                '{{/each}}' +
                '</createRequest>'
```

Error:

`resolveIds { [TypeError: Cannot read property 'body' of undefined]`

**Comment by jonschlinkert** [comment]
> does this module support this kind of usage

it should. if that doesn't work then this would be considered a bug. 

hmm, `body` isn't used anywhere in async-helpers afaik, have you debugged to find out where that variable is defined?

**Comment by RamprasadAkella** [comment]
yeah, thanks for confirming. I think issue on my side only for this, let me debug a little more.
