### ISSUE TITLE
async id not resolved

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/async-helpers#8]
I'm getting an async Id with only one sync helper used. 

Here is the [assemblefile.js](https://gist.github.com/jonschlinkert/af60730f3dc2d9506fff) and the `helpers`object from assemble:

``` js
{ async:
   { partial: { [Function: createdHelper] async: true },
     partials: { [Function: listHelper] async: true },
     layouts: { [Function: listHelper] async: true },
     pages: { [Function: listHelper] async: true },
     docs: { [Function: listHelper] async: true } },
  sync:
   { view: [Function],
     markdown: [Function: markdown],
     log: [Function: log],
     'link-to': [Function: linkTo],
     is: [Function: is],
     foo: [Function],
     assets: [Function: assets] } }
```

I'm building a single view with the following:

``` hbs
{{log this}}
```

and it's rendering:

```
async0_3
```

**Comment by jonschlinkert** [comment]
actually it is being wrapped in a layout (just the default layout from a ST snippet), but the layout is applied without the use of helpers...

**Comment by doowb** [comment]
I'll look into it, but it seems like something isn't trying to resolve the async ids after rendering the templates.

**Comment by jonschlinkert** [comment]
Yeah hopefully we can fix sooner than later. I remember from last year that a lot of people like doing personal blogs and trying the next version on their free time over the holidays

**Comment by doowb** [comment]
This was being caused because an async id from a helper used inside the `{{markdown}}` helper was being parsed and transformed from `__async0_3__` to `<strong>async0_3</strong>`.

Updated the delimiters to `{$ASYNCID$0$3$}` to reduce conflicts.
